language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx-2
  - jruby-18mode
  - jruby-19mode
  - jruby-head

os:
  - linux
  - osx

sudo: false

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: 2.2
    - rvm: jruby-head

before_install: gem install bundler -v 1.10.6

script: bundle exec rake
