language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - ruby-head

os:
  - linux
  - osx

sudo: false

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head

before_install: gem install bundler -v 1.10.6

script: bundle exec rake
